/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/React/这是第二个React文件': RouteRecordInfo<'/React/这是第二个React文件', '/React/这是第二个React文件', Record<never, never>, Record<never, never>>,
    '/React/这是一个React文件': RouteRecordInfo<'/React/这是一个React文件', '/React/这是一个React文件', Record<never, never>, Record<never, never>>,
    '/React/Fucking': RouteRecordInfo<'/React/Fucking', '/React/Fucking', Record<never, never>, Record<never, never>>,
    '/Unity/这是一个Unity文件': RouteRecordInfo<'/Unity/这是一个Unity文件', '/Unity/这是一个Unity文件', Record<never, never>, Record<never, never>>,
    '/Vue/这是一个Vue文件': RouteRecordInfo<'/Vue/这是一个Vue文件', '/Vue/这是一个Vue文件', Record<never, never>, Record<never, never>>,
  }
}
