name: Deploy Docs to Public Repo

on:
    push:
        branches: [main]
    workflow_dispatch:

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout private repo
              uses: actions/checkout@v4

            - name: Install pnpm
              uses: pnpm/action-setup@v4
              with:
                  version: latest
                  run_install: false

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: latest
                  cache: pnpm

            - name: Install dependencies
              run: pnpm install

            - name: Build
              run: pnpm run build

            - name: Deploy to public repo
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                  token: ${{secrets.DOCS_DEPLOY_TOKEN}}
                  repository-name: Msenxy/msenxy.github.io
                  branch: main
                  folder: dist
                  clean: true
